name: GMPermissions
main: GMPermissions\Main
version: 1.0.5
api: [1.12.0,1.13.0,1.14.0,2.0.0]
load: POSTWORLD
author: wolfdale/awzaw
description: Restrict users from changing their own or others gamemode
commands:
 nogm:
  description: "Toggles gamemode changed allowed for yourself by others"
  usage: "/nogm"
  permission: gmchange.nogm
permissions:
  gmchange.others:
    description: Allows users to change others gamemode
    default: op
  gmchange.spectator:
    description: Allows users to gamemode spectator
    default: op
  gmchange.nogm:
    description: Disable your own gamemode changes by others
    default: op
