name: GMPermissions
main: GMPermissions\Main
version: 1.1
api: [2.0.0, 3.0.0-ALPHA1]
load: POSTWORLD
author: wolfdale/awzaw
description: Restrict users from changing their own or others gamemode
commands:
 nogm:
  description: "Toggles gamemode changed allowed for yourself by others"
  usage: "/nogm"
  permission: gmchange.nogm
permissions:
 gmchange:
  default: op
  description: Allows unrestricted changes to gamemode for self and to others
  children:
   gmchange.others:
    description: Allows users to change others gamemode
    default: false
   gmchange.spectator:
    description: Allows users to use spectator mode
    default: false
   gmchange.nogm:
    description: Disable your own gamemode changes by others
    default: false
  gmchange.creative:
    description: Allowed Creative Mode
    default: false